version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: nuget
    directories:
      - "/src/Ulid"
      - "/src/Dapper.Impl"
      - "/src/EFCore.Impl"
      - "/src/LinqToDB.Impl"
      - "/src/DB.Shared"
    schedule:
      interval: "weekly"
