changelog:
  categories:
    - title: "⚠️ BREAKING CHANGES / MIGRATION WARNINGS"
      labels:
        - breaking-change
    - title: "ByteAether.Ulid"
      labels:
        - pkg:Ulid
    - title: "ByteAether.Ulid.AspNetCore"
      labels:
        - pkg:AspNetCore
    - title: "ByteAether.Ulid.EntityFrameworkCore"
      labels:
        - pkg:EFCore
    - title: "ByteAether.Ulid.linq2db"
      labels:
        - pkg:LinqToDB
    - title: "ByteAether.Ulid.Dapper"
      labels:
        - pkg:Dapper
    - title: "ByteAether.Ulid.Cli"
      labels:
        - pkg:Cli
    - title: "Other"
      labels:
        - "*" # Catch-all for PRs that don't match the package labels above
