<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;net6.0;netstandard2.0</TargetFrameworks>
    <OutputType>library</OutputType>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <RootNamespace>ByteAether.Ulid.DB.Shared</RootNamespace>
    <AssemblyName>ByteAether.Ulid.DB.Shared</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ulid\Impl.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.StartsWith('netstandard'))">
    <Compile Include="..\Compatibility\**\*.cs" Link="Compatibility\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.Bcl.Memory" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DB.Shared.Tests" />
    <InternalsVisibleTo Include="ByteAether.Ulid.Dapper" />
    <InternalsVisibleTo Include="ByteAether.Ulid.EntityFrameworkCore" />
    <InternalsVisibleTo Include="ByteAether.Ulid.LinqToDB" />
  </ItemGroup>

</Project>
