<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;net5.0;netstandard2.1;netstandard2.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <OutputType>library</OutputType>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">true</TreatWarningsAsErrors>

    <Deterministic>true</Deterministic>
    <IsAotCompatible>true</IsAotCompatible>
    <InvariantGlobalization>true</InvariantGlobalization>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <Title>Ulid</Title>
    <Description>High-performance, spec-compliant ULIDs engineered to prevent index fragmentation and random-part overflow errors.

Ideal for database primary keys and distributed systems, this library ensures lexicographical sortability and human-readable Base32 encoding. It features configurable protection against enumeration attacks, is fully Native AOT-ready, and offers zero-allocation interoperability with GUIDs, databases, and JSON. Optimized for efficient database writes and robust, timestamped identification in modern .NET.</Description>
    <Authors>Joonatan Uusväli</Authors>
    <Company>ByteAether</Company>
    <Copyright>© $(Authors), $(Company). All rights reserved.</Copyright>

    <RepositoryUrl>https://github.com/ByteAether/Ulid</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <PackageId>ByteAether.Ulid</PackageId>
    <PackageTags>ulid;identifier;unique-id;unique-identifier;universal-identifier;lexicographically-sortable;lexicographical;id-generator;globally-unique;globally-unique-identifier;distributed-systems;database;performance;guid;uuid;sortable;human-readable;monotonic;primary-key;base32;cross-platform;aot-ready</PackageTags>
    <PackageProjectUrl>$(RepositoryUrl)/tree/v$(PackageVersion)</PackageProjectUrl>
    <PackageReleaseNotes>See $(RepositoryUrl)/releases/tag/v$(PackageVersion)</PackageReleaseNotes>
    <PackageReadmeFile>PACKAGE.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>logo.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Memory" Version="4.6.3"/>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2"/>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' ">
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="PACKAGE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\assets\logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
