<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;net5.0;netstandard2.1;netstandard2.0</TargetFrameworks>
    <OutputType>library</OutputType>
    <IsAotCompatible>true</IsAotCompatible>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Title>ByteAether.Ulid - High-Performance ULID for .NET</Title>
    <Description>A fast, spec-compliant ULID (Universally Unique Lexicographically Sortable Identifier) implementation for modern .NET. Optimized for database primary keys, Native AOT, zero-allocation, GUID interoperability, and high-performance serialization.</Description>

    <PackageId>ByteAether.Ulid</PackageId>
    <PackageIcon>logo_ulid.png</PackageIcon>
    <PackageTags>ulid;id;uuid;guid;id-generator;unique-id;aot-ready;efcore;dotnet;csharp</PackageTags>
    <PackageReadmeFile>PACKAGE.md</PackageReadmeFile>

    <RootNamespace>ByteAether.Ulid</RootNamespace>
    <AssemblyName>ByteAether.Ulid</AssemblyName>
  </PropertyGroup>

  <ItemGroup Condition="$(TargetFramework.StartsWith('netstandard'))">
    <Compile Include="..\Compatibility\**\*.cs" Link="Compatibility\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="Microsoft.Bcl.Memory" Version="10.0.9" PrivateAssets="All"/>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" PrivateAssets="All"/>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' ">
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" PrivateAssets="All"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\..\assets\logo_ulid.png" Pack="true" PackagePath="\" Visible="false" />
    <None Include="PACKAGE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
