<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>

    <RootNamespace>ByteAether.Ulid.Benchmarks</RootNamespace>
  </PropertyGroup>

  <Target Name="SkipBenchmarkOnCI" BeforeTargets="BeforeBuild;Build;Restore" Condition="'$(IsCIBuild)' == 'true'">
    <PropertyGroup>
      <DesignTimeBuild>true</DesignTimeBuild>
      <BuildingProject>false</BuildingProject>
    </PropertyGroup>
    <Message Importance="high" Text="Skipping benchmark project compilation for CI loop." />
  </Target>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="NetUlid" Version="2.1.0" />
    <PackageReference Include="NUlid" Version="1.7.3" />
    <PackageReference Include="Ulid" Version="1.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ulid\Impl.csproj" />
  </ItemGroup>

</Project>
