<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>

    <RootNamespace>ByteAether.Ulid.Benchmarks</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" VersionOverride="0.15.8" />
    <PackageReference Include="NetUlid" VersionOverride="2.1.0" />
    <PackageReference Include="NUlid" VersionOverride="1.7.3" />
    <PackageReference Include="Ulid" VersionOverride="1.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ulid\Impl.csproj" />
  </ItemGroup>

</Project>
