<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;net7.0</TargetFrameworks>
    <IsTestProject>true</IsTestProject>
    <NoWarn>NU1903</NoWarn>

    <RootNamespace>ByteAether.Ulid.Dapper.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dapper\Dapper.Impl.csproj" />
  </ItemGroup>

</Project>
