<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <UseDataCollector/>

    <RootNamespace>ByteAether.Ulid.Tests</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
    <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;net472</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xunit.Combinatorial" Version="1.6.24" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ulid\Impl.csproj" />
  </ItemGroup>

</Project>
