<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <SupportedImplFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0</SupportedImplFrameworks>

    <IsTestProject Condition="$(SupportedImplFrameworks.Contains('$(ImplTargetFramework)'))">true</IsTestProject>
    <RootNamespace>ByteAether.Ulid.AspNetCore.IntegrationTests.OpenApi</RootNamespace>
    <DefineConstants Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(ImplTargetFramework)', 'net9.0'))">$(DefineConstants);IMPL_NET9_OR_GREATER</DefineConstants>
    <InterceptorsNamespaces Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(ImplTargetFramework)', 'net9.0'))">$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.OpenApi" VersionOverride="1.2.3" Condition="'$(ImplTargetFramework)' != 'net9.0' and '$(ImplTargetFramework)' != 'net10.0'" />
    <PackageReference Include="Microsoft.OpenApi" VersionOverride="1.6.17" Condition="'$(ImplTargetFramework)' == 'net9.0'" />
    <PackageReference Include="Microsoft.OpenApi" VersionOverride="2.7.5" Condition="'$(ImplTargetFramework)' == 'net10.0'" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" VersionOverride="9.0.0" Condition="'$(ImplTargetFramework)' == 'net9.0'" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" VersionOverride="10.0.0" Condition="'$(ImplTargetFramework)' == 'net10.0'" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" VersionOverride="6.0.0" Condition="'$(ImplTargetFramework)' != 'net10.0'" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" VersionOverride="10.0.0" Condition="'$(ImplTargetFramework)' == 'net10.0'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspNetCore\AspNetCore.Impl.csproj" SetTargetFramework="TargetFramework=$(ImplTargetFramework)" />
  </ItemGroup>
</Project>
