<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- NuGet Packaging -->
    <IsPackable>false</IsPackable>
    <Deterministic>true</Deterministic>
    <InvariantGlobalization>true</InvariantGlobalization>

    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <Authors>Joonatan Uusväli</Authors>
    <Company>ByteAether</Company>
    <Copyright>© $(Authors), $(Company). All rights reserved.</Copyright>

    <RepositoryUrl>https://github.com/ByteAether/Ulid</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <PackageProjectUrl>$(RepositoryUrl)/tree/v$(PackageVersion)</PackageProjectUrl>
    <PackageReleaseNotes>See $(RepositoryUrl)/releases/tag/v$(PackageVersion)</PackageReleaseNotes>

    <PackageLicenseExpression>MIT</PackageLicenseExpression>

  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'CI-Release'"><Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>

    <PublishRelease>true</PublishRelease>
    <PackRelease>true</PackRelease>

    <RuntimeIdentifierGraphPath Condition="'$(RuntimeIdentifierGraphPath)' == ''"></RuntimeIdentifierGraphPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'CI-Debug'">
    <Optimize>false</Optimize>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="$(MSBuildThisFileDirectory)..\LICENSE" />
  </ItemGroup>

  <ItemGroup Condition="$(IsTestProject) == 'true'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" Condition="'$(TargetFramework)' == 'net6.0' Or '$(TargetFramework)' == 'net7.0'"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" Condition="'$(TargetFramework)' != 'net6.0' And '$(TargetFramework)' != 'net7.0'"/>

    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2" Condition="'$(TargetFramework)' == 'net6.0' Or '$(TargetFramework)' == 'net7.0'">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" Condition="'$(TargetFramework)' != 'net6.0' And '$(TargetFramework)' != 'net7.0'">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="xunit" Version="2.9.3" />

    <Using Include="Xunit"/>
  </ItemGroup>
</Project>
