<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Bcl.Memory" Version="10.0.10" />
    <PackageVersion Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />

    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.9" />
    <PackageVersion Include="linq2db" Version="6.3.0" />

    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="Xunit.Combinatorial" Version="2.1.41" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
