<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;net7.0</TargetFrameworks>
    <IsTestProject>true</IsTestProject>
    <NoWarn>NU1903</NoWarn>

    <RootNamespace>ByteAether.Ulid.LinqToDB.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="linq2db" Version="6.3.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LinqToDB\LinqToDB.Impl.csproj" />
  </ItemGroup>

</Project>
