<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <UseDataCollector/>

    <RootNamespace>ByteAether.Ulid.DB.Shared.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DB.Shared\DB.Shared.csproj" />
    <ProjectReference Include="..\Ulid\Impl.csproj" />
  </ItemGroup>

</Project>
