name: Build and Test

on:
  push:
    branches:
      - main
    paths:
      - src/**
  pull_request:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Get Short SHA
      id: vars
      run: echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: |
          10.x
          9.x
          8.x
          7.x
          6.x
          5.x

    - name: Restore dependencies
      run: dotnet restore src/ByteAether.Ulid.slnx -p:Configuration=CI-Release

    - name: Build
      run: dotnet build src/ByteAether.Ulid.slnx --configuration CI-Release --no-restore

    - name: Upload DLLs
      uses: actions/upload-artifact@v7
      with:
        name: dlls-${{ steps.vars.outputs.sha_short }}
        path: | 
          ./**/Ulid/bin/**/*.dll
          ./**/EFCore.Impl/bin/**/*.dll

    - name: Run tests
      continue-on-error: true
      run: dotnet test src/ByteAether.Ulid.slnx --configuration CI-Release --no-build --verbosity normal --logger "trx"

    - name: Upload test results
      uses: actions/upload-artifact@v7
      with:
        name: test-results-${{ steps.vars.outputs.sha_short }}
        path: ./**/TestResults/**/*.trx

    - name: Pack
      run: dotnet pack src/ByteAether.Ulid.slnx --configuration CI-Release -p:ContinuousIntegrationBuild=true -p:PackageVersion=0.0.0-ci-${{ steps.vars.outputs.sha_short }} -p:PackageReleaseNotes="CI Build ${{ steps.vars.outputs.sha_short }}" --output ./output

    - name: Upload NuGet package
      uses: actions/upload-artifact@v7
      with:
        name: nugets-${{ steps.vars.outputs.sha_short }}
        path: ./output/*.nupkg
