name: ULID AOT Compatibility Test

on:
  push:
    branches:
      - main
    paths:
      - src/**
  pull_request:
    branches:
      - main
    paths:
      - src/**

jobs:
  build-and-test-aot:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: Build & Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Setup .NET 10.0.x
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore src/ByteAether.Ulid.slnx -p:Configuration=CI-Release --use-current-runtime -p:SelfContained=true

    - name: Build and Publish AOT Console Application (${{ matrix.os }})
      run: dotnet publish src/Ulid.Tests.AotConsole/Tests.AotConsole.csproj --configuration CI-Release --no-restore --use-current-runtime --self-contained true -o ./publish

    - name: Run AOT Compiled Application (${{ matrix.os }})
      shell: bash # Ensure bash is used on Windows as well for consistent pathing syntax (./)
      run: ./publish/Tests.AotConsole
